
var Product = require('../models/product');
const db = require('../src/db');

db.connectToServer().then(() => {
  console.log('Connected to database ');

  const products = [
    new Product({
      name: 'Running shoes',
      category: 'sports',
      subCategory: 'running',
      gender: 'm',
      brand: 'adidas',
      image: 'https://dks.scene7.com/is/image/dkscdn/18BROMRVL2BLKGRYXMNS_Oreo_is?wid=1080&fmt=jpg',
      stock: [{size: 7, count: 2}, {size: 8, count: 5}, {size: 9, count: 3}],
      description:'running shoes',
      cost: 160,
    }),
    new Product({
      name: 'Hiking Boots',
      category: 'boots',
      gender: 'm',
      brand: 'new balance',
      image: 'https://images.sportsdirect.com/images/products/12125840_l.jpg',
      stock: [{size: 8, count: 3}, {size: 9, count: 5}, {size: 10, count: 3}],
      description:'Hiking boots for outdoors',
      cost: 190,
    }),
    new Product({
      name: 'Dress Shoes',
      category: 'fancy',
      gender: 'm',
      brand: 'nike',
      image: 'https://images.josbank.com/is/image/JosBank/40KL_01_JOSEPH_ABBOUD_HERITAGE_BLACK_MAIN?$browse_thumbnail$?$browse_thumbnail$',
      stock: [{size: 7, count: 2}, {size: 8, count: 1}, {size: 9, count: 7}],
      description:'Fancy shoes for that special meeting',
      cost: 400,
    }),
    new Product({
      name: '2 Inch Heels',
      category: 'fancy',
      gender: 'f',
      brand: 'polo',
      image: 'https://cdn.shopify.com/s/files/1/1117/1266/files/collection-page-2inch-heels-270x269.jpg?14898049490607918996',
      stock: [{size: 5, count: 2}, {size: 6, count: 3}, {size: 7, count: 6}],
      description:'Some heels',
      cost: 100,
    }),
    new Product({
      name: 'Downshifter',
      category: 'sports',
      gender: 'm',
      brand: 'nike',
      image: 'https://images.sportsdirect.com/images/products/12125840_l.jpg',
      stock: [{size: 3, count: 3}, {size: 4, count: 6}, {size: 5, count: 1}],
      description:'These Nike Downshifter trainers feature lace fastening and a padded ankle collar for a secure fit',
      cost: 320,
    }),
    new Product({
      name: 'Shox Enigma',
      category: 'sports',
      gender: 'f',
      brand: 'nike',
      image: 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/zbmmjrnldlnq6yci8wpq/shox-enigma-shoe-jXhp4B.jpg',
      stock: [{size: 5, count: 3}, {size: 7, count: 5}, {size: 4, count: 2}],
      description:'The Nike Shox Enigma brings the look and feel of the early millennium to todays streets with crazy cushioning and stability',
      cost: 40,
    }),
    new Product({
      name: 'Olivia Kim Air Max 98',
      category: 'sports',
      gender: 'f',
      brand: 'nike',
      image: 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/nf1k518dpg0pqsyinkq9/olivia-kim-air-max-98-womens-shoe-M6k3zK.jpg',
      stock: [{size: 2, count: 8}, {size: 5, count: 7}, {size: 8, count: 2}],
      description:'The Nike x Olivia Kim Air Max 98 celebrates the music and culture of NYC as remembered by designer Olivia',
      cost: 80,
    }),
    new Product({
      name: 'Pegasus 36 FlyEase',
      category: 'sports',
      gender: 'm',
      brand: 'nike',
      image: 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/pcogofhncmrvjsitoj19/pegasus-36-flyease-extra-wide-mens-running-shoe-1Fb6sV.jpg',
      stock: [{size: 3, count: 4}, {size: 4, count: 7}, {size: 5, count: 10}],
      description:'The Nike Air Zoom Pegasus 36 FlyEase maintains everything you love about the Pegasus and adds a zipper for effortless on and off',
      cost: 220,
    }),
    new Product({
      name: 'React Ianga',
      category: 'boots',
      gender: 'm',
      brand: 'nike',
      image: 'https://images.sportsdirect.com/images/products/12125840_l.jpg',
      stock: [{size: 3, count: 3}, {size: 4, count: 6}, {size: 5, count: 1}],
      description:'The Nike React Ianga takes elements from a jungle boot and mixes them with modern, technical details',
      cost: 60,
    }),
    new Product({
      name: 'ULTRABOOST',
      category: 'sports',
      gender: 'm',
      brand: 'adidas',
      image: 'https://assets.adidas.com/images/w_600,f_auto,q_auto:sensitive,fl_lossy/79f8b82f203b41ecb700a9ce011c7a65_9366/Ultraboost_19_Shoes_White_B37707_01_standard.jpg',
      stock: [{size: 1, count: 1}, {size: 2, count: 4}, {size: 3, count: 6}],
      description:' These adidas Ultraboost Shoes have a foot-hugging knit upper that stretches and supports with every step',
      cost: 150,
    }),
    new Product({
      name: 'HARDEN VOL. 4',
      category: 'sports',
      gender: 'm',
      brand: 'adidas',
      image: 'https://assets.adidas.com/images/w_600,f_auto,q_auto:sensitive,fl_lossy/63c23020facd4ce7a49caa07003a2b07_9366/Harden_Vol._4_Shoes_Black_F97187_01_standard.jpg',
      stock: [{size: 2, count: 8}, {size: 6 count: 2}, {size: 7, count: 7}],
      description:'Featuring ultra-lightweight and responsive midsole cushioning, they have a midfoot band for the added lockdown and stability needed to make hard, decisive cuts',
      cost: 130,
    }),
    new Product({
      name: 'CONTINENTAL 80',
      category: 'sports',
      gender: 'm',
      brand: 'adidas',
      image: 'https://assets.adidas.com/images/w_600,f_auto,q_auto:sensitive,fl_lossy/8df5ab4346d7475ebb08a91500a047d3_9366/Continental_80_Shoes_White_G27706_01_standard.jpg',
      stock: [{size: 3, count: 3}, {size: 4, count: 6}, {size: 5, count: 1}],
      description:'The split rubber cupsole and swooping two-tone stripe nail the look',
      cost: 270,
    }),
    new Product({
      name: 'KAPTIR X',
      category: 'sports',
      gender: 'f',
      brand: 'adidas',
      image: 'https://assets.adidas.com/images/w_600,f_auto,q_auto:sensitive,fl_lossy/8a84931c811345e88c63aa63010e1be7_9366/Kaptir_X_Shoes_White_EE9969_01_standard.jpg',
      stock: [{size: 1, count: 7}, {size: 4, count: 9}, {size: 5, count: 15}],
      description:'Layers of plush cushioning combine with a foot-hugging fit for comprehensive comfort',
      cost: 190,
    }),
    new Product({
      name: 'ASWEERUN',
      category: 'sports',
      gender: 'f',
      brand: 'adidas',
      image: 'https://assets.adidas.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/9c5c193332904c7f8f67aa9b01354e42_9366/Asweerun_Shoes_Pink_EE8502_01_standard.jpg',
      stock: [{size: 2, count: 7}, {size: 4, count: 96}, {size: 5, count: 1}],
      description:'The rubber outsole is designed to provide a secure grip, and the moulded heel counter helps keep you stable on uneven terrain',
      cost: 290,
    }),
    new Product({
      name: 'NITE JOGGER',
      category: 'sports',
      gender: 'f',
      brand: 'adidas',
      image: 'https://assets.adidas.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/fb5a5538786e422c8162aaaa00dc0fbe_9366/Nite_Jogger_Shoes_White_FV3586_01_standard.jpg',
      stock: [{size: 3, count: 2}, {size: 7, count: 1}, {size: 8, count: 6}],
      description:'A revival of the 1980 Nite Jogger, these retro shoes flash bright with reflective details',
      cost: 240,
    }),
    new Product({
      name: 'ASTRO KICK TRAINERS',
      category: 'sports',
      gender: 'm',
      brand: 'puma',
      image: 'https://images.puma.net/images/369115/03/sv01/fnd/AUS/w/1000/h/1000/bg/255,255,255',
      stock: [{size: 2, count: 1}, {size: 5, count: 1}, {size: 9, count: 1}],
      description:'Featuring a branded tongue and the classic PUMA Formstrip at the sides, these sneakers can be dressed up or down, no matter the occasion',
      cost: 90,
    }),
    new Product({
      name: 'THUNDER SPECTRA SNEAKERS',
      category: 'sports',
      gender: 'm',
      brand: 'puma',
      image: 'https://images.puma.net/images/367516/10/sv01/fnd/AUS/w/1000/h/1000/bg/255,255,255',
      stock: [{size: 3, count: 3}, {size: 7, count: 4}, {size: 8, count: 6}],
      description:'The exaggerated tooling, the blown-up proportions and the loud color blocking reserve a spot for the Thunder on the international runways',
      cost: 180,
    }),
    new Product({
      name: 'LQDCELL OMEGA LAB TRAINING SHOES',
      category: 'sports',
      gender: 'm',
      brand: 'puma',
      image: 'https://images.puma.net/images/370928/02/sv01/fnd/AUS/w/1000/h/1000/bg/255,255,255',
      stock: [{size: 7, count: 1}, {size: 11, count: 2}, {size: 13, count: 7}],s
      description:'LQDCELL Omega Lab takes inspiration from organic shapes and layers found in nature, combining them with LQDCELL Technology: oft yet sturdy hexagonal cells for enhanced cushioning and comfort',
      cost: 390,
    }),
    new Product({
      name: 'PACER NEXT CAGE ST2',
      category: 'sports',
      gender: 'f',
      brand: 'puma',
      image: 'https://images.puma.net/images/367660/02/sv01/fnd/AUS/w/1000/h/1000/bg/255,255,255',
      stock: [{size: 5, count: 2}, {size: 6, count: 1}, {size: 8, count: 6}],
      description:'Its tongue-less, slip-on construction creates a sock-like fit, making it ultra-comfortable to boot',
      cost: 310,
    }),
    new Product({
      name: 'TETRIS RS-X TRAINERS',
      category: 'sports',
      gender: 'f',
      brand: 'puma',
      image: 'https://assets.adidas.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/fb5a5538786e422c8162aaaa00dc0fbe_9366/Nite_Jogger_Shoes_White_FV3586_01_standard.jpg',
      stock: [{size: 5, count: 6, {size: 7, count: 2}, {size: 12, count: 8}],
      description:'RS-X stands for RE-IMAGINATION as the archive technology is reimagined in a future-focused, tech-style',
      cost: 220,
    }),
    new Product({
      name: 'KARL LAGERFELD CALI',
      category: 'sports',
      gender: 'f',
      brand: 'puma',
      image: 'https://images.puma.net/images/370057/01/sv01/fnd/AUS/w/1000/h/1000/bg/255,255,255',
      stock: [{size: 1, count: 6}, {size: 6, count: 2}, {size: 13, count: 6}],
      description:'Originally a laid-back training sneaker, the Cali has been given an edge with the progressive rubber tooling whilst the upper remains true to the original',
      cost: 110,
    }),
    new Product({
      name: 'CLASSIC SLIDES',
      category: 'slides',
      gender: 'm',
      brand: 'reebok',
      image: 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/14e5c82495094af48c3baa4201331a1f_9366/Reebok_Classic_Slides_Red_DV9408_01_standard.jpg',
      stock: [{size: 5, count: 6}, {size: 6, count: 2}, {size: 7, count: 6}],
      description:'Go from beach to street, these easygoing slides slip on for a laid-back vibe.',
      cost: 30,
    }),
    new Product({
      name: 'slides max',
      category: 'slides',
      gender: 'f',
      brand: 'reebok',
      image: 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/824a8378e7204e968f31aa4c013dfa8b_9366/Reebok_Classic_Slides_Pink_DV6905_01_standard.jpg',
      stock: [{size: 1, count: 6}, {size: 6, count: 2}, {size: 13, count: 6}],
      description:'A herringbone outsole provides traction on sand and sidewalk.',
      cost: 15,
    }),
    new Product({
      name: 'slippers of agility',
      category: 'slides',
      gender: 'f',
      brand: 'reebok',
      image: 'https://assets.reebok.com/images/w_840,h_840,f_auto,q_auto:sensitive,fl_lossy/727a2a0bce6b4ccbb98faa47001d999a_9366/Reebok_Classic_Slides_Pink_DV9402_01_standard.jpg',
      stock: [{size: 3, count: 5}, {size: 2, count: 9}, {size: 12, count: 1}],
      description:'A contrast Vector logo adds sporty style to the strap',
      cost: 10,
    }),
    new Product({
      name: 'Military Lace up Combat',
      category: 'boots',
      gender: 'f',
      brand: 'reebok',
      image: 'https://images-na.ssl-images-amazon.com/images/I/71e-ChhtG3L._UY695_.jpg',
      stock: [{size: 2, count: 6}, {size: 4, count: 2}, {size: 6, count: 6}],
      description:' Buy these guilt-free, knowing your purchase is making no dent in the environment! Eco-friendly and in control',
      cost: 50,
    }),
    new Product({
      name: 'The Captain',
      category: 'boots',
      gender: 'm',
      brand: 'reebok',
      image: 'https://cdn.shopify.com/s/files/1/0419/1525/products/Captain_Brandy_34G2_1024x1024.jpg?v=1570128215',
      stock: [{size: 3, count: 4}, {size: 5, count: 7}, {size: 9, count: 4}],
      description:'This minimalist cap-toe features a carefully designed stitch over the toe to add style while letting the quality of the materials do most of the talking',
      cost: 110,
    }),
    new Product({
      name: 'BROSUS CAP TOE',
      category: 'boots',
      gender: 'm',
      brand: 'reebok',
      image: 'https://dsw.scene7.com/is/image/DSWShoes/317277_200_ss_01?$pdp-image$',
      stock: [{size: 4, count: 5}, {size: 6, count: 8}, {size: 12, count: 2}],
      description:'Right on trend, but with a unique factor that will make you stand out from the crowd',
      cost: 310,
    }),
    new Product({
      name: 'THOMS LEATHER LACED-UPBROSUS CAP TOE',
      category: 'fancy',
      gender: 'm',
      brand: 'asics',
      image: 'https://www.unze.com.pk/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/g/s/gs5105_30.jpg',
      stock: [{size: 4, count: 4}, {size: 6, count: 5}, {size: 10, count: 14}],
      description:'For a sharp and impressive looks wear these traditional brogue designed leather shoes',
      cost: 240,
    }),
    new Product({
      name: 'Black mercinary medic pyros',
      category: 'fancy',
      gender: 'm',
      brand: 'asics',
      image: 'https://5.imimg.com/data5/VJ/BM/MY-19338883/kids-wear-500x500.jpg',
      stock: [{size: 9, count: 2}, {size: 11, count: 4}, {size: 13, count: 5}],
      description:'Our products are high in demand due to their premium quality, seamless finish and affordable prices',
      cost: 80,
    }),
    new Product({
      name: 'Synthetic Leather Casual Pudges',
      category: 'fancy',
      gender: 'm',
      brand: 'puma',
      image: 'https://rukminim1.flixcart.com/image/880/1056/jm6mjrk0/shoe/p/k/7/tr-blck-g-10-gstm-black-original-imaf95h6justhhgq.jpeg?q=50',
      stock: [{size: 1, count: 2}, {size: 4, count: 5}, {size: 12, count: 7}],
      description:'Affordable shoes with a great new shine look',
      cost: 160,
    }),
    new Product({
      name: 'Abaddon Pumps High Heels',
      category: 'fancy',
      gender: 'f',
      brand: 'adidas',
      image: 'https://www.dhresource.com/0x0/f2/albu/g7/M01/AD/A1/rBVaSVtW4SiAFh-YAAEF-A31PRM029.jpg',
      stock: [{size: 4, count: 8}, {size: 7, count: 2}, {size: 13, count: 1}],
      description:'Top material, top layer cowhide, what more can you ask for',
      cost: 190,
    }),
    new Product({
      name: 'Lady Black High Heel',
      category: 'fancy',
      gender: 'f',
      brand: 'polo',
      image: 'https://my-test-11.slatic.net/p/04c7ebdf2cd4d3eae03fad764e9e09c0.jpg_340x340q80.jpg_.webp',
      stock: [{size: 4, count: 5}, {size: 6, count: 8}, {size: 12, count: 2}],
      description:'Right on trend, but with a unique factor that will make you stand out from the crowd',
      cost: 220,
    }),
    new Product({
      name: 'Lina Sweet Bowknot Flats Bowtie pointed Toe',
      category: 'fancy',
      gender: 'f',
      brand: 'new balance',
      image: 'https://image.kilimall.com/kenya/shop/store/goods/781/2016/10/781_05312713150127501_720.jpg',
      stock: [{size: 3, count: 4}, {size: 5, count: 19}, {size: 8, count: 12}],
      description:'Unique look with a great twist in style',
      cost: 100,
    }),
  ];

  let count = 0;

  products.forEach((product) => {
    product.save().then((output) => {
      console.log("adding");
      count++;
      if(count === products.length){
        db.getDb().disconnect();
      }
    }).catch((error) => {
      console.error(error);
    });
  });
  
}).catch((error) =>{
  console.log('could not connect to the database');
  console.log(error);
});